Confirmation dialog
NITTC-ComputerClub/Udon.Client.Web pull request #1
Opened 2020-11-19 09:09 UTC by RAINeko256

打刻用のダイアログが完成しました。
（あくまでダイアログのみで、ダイアログ上の打刻ボタンを押しても反応しません(consoleにokと表示されるだけ)

2020-11-19 09:13 UTC, Chaha1n commented
React何もわからんので、レビューどうしようという感じです(とりあえず見ます)

2020-11-19 16:04 UTC, siketyan commented
寝て起きたら見ます！

2020-11-20 02:55 UTC, siketyan requested changes
npm install **--save** @material-ui/core をしてないかな？もしくは package.json の差分がコミットされてないです

![image](https://user-images.githubusercontent.com/12772118/99752177-24707200-2b27-11eb-9946-d45080060502.png)

2020-11-20 02:58 UTC, siketyan requested changes
全体的にですが，インデントがスペースとタブで混ざっててぐちゃぐちゃになってしまってます．エディタの設定を確認してください 🙇‍♂️

2020-11-20 02:59 UTC, siketyan commented
Description にある通りの動作は確認できました！
`/main` を `/` にしてもいいかもです．

2020-11-20 10:37 UTC, RAINeko256 commented
できれば明日package.jsonを追加するのと、インデント問題を解決します！
ありがとうございます！🙇‍♂️

2020-11-22 10:21 UTC, siketyan requested changes

2020-11-22 10:21 UTC, siketyan commented on debug.log
> +[1111/172855.163:ERROR:directory_reader_win.cc(43)] FindFirstFile: �w�肳�ꂽ�p�X��������܂���B (0x3)
なんのログか知らないけどいらないです

2020-11-22 11:55 UTC, RAINeko256 commented on debug.log
> +[1111/172855.163:ERROR:directory_reader_win.cc(43)] FindFirstFile: �w�肳�ꂽ�p�X��������܂���B (0x3)
間違えて追加してしまったものです
削除しました

2020-11-22 11:57 UTC, RAINeko256 commented
インデントを修正し、/mainを/に変更しました。

2020-11-22 23:52 UTC, siketyan commented
@RAINeko256 package.json は……？

2020-11-23 00:22 UTC, RAINeko256 commented
> @RAINeko256 package.json は……？

firstのときから変更がないみたいで...
最初にレビューしてもらったときにうまく動作せず、確かに変更したはずなんですが、確認してもfirstコミットと同じままでちゃんと動作しています

2020-11-23 00:24 UTC, siketyan commented
@RAINeko256 
`npm i --save @material-ui/core すれば差分出るはず

2020-11-23 00:34 UTC, RAINeko256 commented
@siketyan 変更されました ありがとうございます！ただ今追加しました

2020-11-23 01:55 UTC, siketyan approved these changes
動作確認しました

2020-11-23 01:55 UTC, siketyan commented
@Chaha1n レビューお願いします 🙏

2020-11-23 02:20 UTC, Chaha1n approved these changes
動作確認できました👌

2020-11-23 15:44 UTC, siketyan commented
@RAINeko256

2020-11-24 01:16 UTC, merged